import { cookies } from "next/headers";

export const routes = {
  home: "/",
  about: "/about-us",
  contact: "/contact",
  accessibility: "/accessibility",
  help: "/help",
  LearnMore: "/learn-more",
  privacy: "/privacy",
  generalProjectsView: "/projects",
  report: "/report",
  safetyAndGuidelines: "/safety",
  successStories: "/success-stories",
  terms: "/terms",
  opportunities: "/opportunities",
  postProject: "/post-projects",
  cookies: "/cookies",

  // Authentication routes
  login: "/login",
  confirmation: "/confirm",
  confirmEmail: "/confirm-email",
  forgotPassword: "/forgot-password",
  agencyCheckMail: "/agency-checkmail",
  approvalPending: "/approval-pending",
  onboarding: "/onboarding",
  registerAgency: "/register-agency",
  registerVolunteer: "/register-volunteer",
  volunteerCheckMail: "/volunteer-checkmail",
  agencyOnboarding: "/onboarding/agency",
  volunteerOnboarding: "/onboarding/volunteer",

  dashboard: "/dashboard",

  // Volunteer dashboard routes
    volunteerDashboard: "/volunteer/dashboard",
    volunteerFindOpportunity: "/volunteer/find-opportunity",
    volunteerProfile: "/volunteer/profile",
    volunteerMatchingProjects: "/volunteer/matching-projects",
    volunteerProjects: "/volunteer/projects",
    volunteerViewProject: (id: string) => `/volunteer/projects/${id}`,
    volunteerProjectProjectManagement: (id: string) => `/volunteer/projects/${id}/project_management`,
    volunteerNotifications: "/volunteer/notifications",
    volunteerProjectManagement: "/volunteer/project-management",
    volunteerRequests: "/volunteer/requests",
    volunteerSettings: "/volunteer/settings",

    // Agency dashboard routes
    agencyDashboard: "/agency/dashboard",
    agencyAnalytics: "/agency/analytics",
    agencyProjects: "/agency/projects",
    agencyViewProject: (projectId: string) => `/agency/projects/${projectId}`,
    agencyProjectRecommendations: (projectId: string) => `/agency/projects/${projectId}/recommendations`,
    agencyEditProject: (projectId: string) => `/agency/projects/${projectId}/edit`,
    agencyNotifications: "/agency/notifications",
    agencyProfile: "/agency/profile",
    agencySettings: "/agency/settings",

    // super admin dashboard routes
    superAdminDashboard: "/super-admin/dashboard",
    superAdminAgencies: "/super-admin/agencies",
    superAdminViewAgency: (id: string) => `/super-admin/agencies/${id}`,
    superAdminAdmins: "/super-admin/admins",
    superAdminViewAdmin: (adminId: string) => `/super-admin/admins/${adminId}`,
    superAdminVolunteers: "/super-admin/volunteers",
    superAdminViewVolunteer: (volunteerId: string) => `/super-admin/volunteers/${volunteerId}`,
    superAdminProjects: "/super-admin/projects",
    superAdminViewProject: (projectId: string) => `/super-admin/projects/${projectId}`,
    superAdminEditProject: (projectId: string) => `/super-admin/projects/${projectId}/edit`,
    superAdminInviteAdmin: "/super-admin/invite-admin",
    superAdminNotifications: "/super-admin/notifications",
    superAdminSettings: "/super-admin/settings",
    superAdminUsers: "/super-admin/users",
    superAdminViewUser: (id: string) => `/super-admin/users/${id}`,
    superAdminProfile: "/super-admin/profile",
    superAdminVerifyEmail: "/super-admin/verify-email",

    // Admin dashboard routes
    adminDashboard: "/admin/dashboard",
    adminAgencies: "/admin/agencies",
    adminViewAgency: (id: string) => `/admin/agencies/${id}`,
    adminVolunteers: "/admin/volunteers",
    adminViewVolunteer: (volunteerId: string) => `/admin/volunteers/${volunteerId}`,
    adminProjects: "/admin/projects",
    adminViewProject: (projectId: string) => `/admin/projects/${projectId}`,
    adminEditProject: (projectId: string) => `/admin/projects/${projectId}/edit`,
    adminNotifications: "/admin/notifications",
    adminEmailConfirmations: "/admin/email-confirmations",
    adminSettings: "/admin/settings",
    adminProfile: "/admin/profile",


};
